{
 "title": "consumer",
 "description": "mosn request info",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "服务名",
    "query": "label_values(mosn_request_total{}, service)"
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(mosn_request_total{service=\"$service\", listener=\"egress_dubbo\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "请求耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "downstream_request_time{instance=\"$instance\",listener=\"egress_dubbo\"}",
     "legendFormat": "{{percentile}}"
    }
   ]
  },
  {
   "title": "请求成功数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (service, method) (increase(mosn_response_succ_total{listener=\"egress_dubbo\",service=\"$service\", instance=\"$instance\"}[1m])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "请求失败数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (service, method) (increase(mosn_response_fail_total{listener=\"egress_dubbo\",service=\"$service\", instance=\"$instance\"}[1m])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "平均响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "downstream_request_time{instance=\"$instance\",listener=\"egress_dubbo\",percentile=\"P50\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "downstream_connection_active{listener=\"egress_dubbo\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最小响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "downstream_request_time_min{listener=\"egress_dubbo\", instance=\"$instance\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "最大响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "downstream_request_time_max{listener=\"egress_dubbo\", instance=\"$instance\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "入站流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(downstream_bytes_read_total{listener=\"egress_dubbo\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "出站流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "rate(downstream_bytes_write_total{listener=\"egress_dubbo\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "请求数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum by (service, method) (increase(mosn_request_total{service=\"$service\", instance=\"$instance\"}[1m])))",
     "legendFormat": "{{service}}-{{method}}"
    }
   ]
  }
 ]
}